DISEASE_SPECIALITY = {
    "Diabetes":                "Endocrinologist",
    "Heart attack":            "Cardiologist",
    "Hypertension":            "Cardiologist",
    "Pneumonia":               "Pulmonologist",
    "Tuberculosis":            "Pulmonologist",
    "Migraine":                "Neurologist",
    "Paralysis (brain hemorrhage)": "Neurologist",
    "Fungal infection":        "Dermatologist",
    "Psoriasis":               "Dermatologist",
    "Acne":                    "Dermatologist",
    "Chicken pox":             "Dermatologist",
    "Urinary tract infection": "Urologist",
    "Jaundice":                "Gastroenterologist",
    "Gastroenteritis":         "Gastroenterologist",
    "Peptic ulcer disease":    "Gastroenterologist",
    "Malaria":                 "General Physician",
    "Dengue":                  "General Physician",
    "Typhoid":                 "General Physician",
    "Common Cold":             "General Physician",
    "Arthritis":               "Orthopedist",
    "Osteoarthristis":         "Orthopedist",
    "Allergy":                 "Allergist",
    "Hypothyroidism":          "Endocrinologist",
    "Hyperthyroidism":         "Endocrinologist",
    "Hypoglycemia":            "Endocrinologist",
    "Bronchial Asthma":        "Pulmonologist",
    "Varicose veins":          "Vascular Surgeon",
    "AIDS":                    "Infectious Disease Specialist",
    "Hepatitis A":             "Gastroenterologist",
    "Hepatitis B":             "Gastroenterologist",
    "Hepatitis C":             "Gastroenterologist",
    "Hepatitis D":             "Gastroenterologist",
    "Hepatitis E":             "Gastroenterologist",
    "Alcoholic hepatitis":     "Gastroenterologist",
    "Drug Reaction":           "Dermatologist",
    "Dimorphic hemorrhoids(piles)": "Gastroenterologist",
    "Chronic cholestasis":     "Gastroenterologist",
    "Cervical spondylosis":    "Orthopedist",
    "Impetigo":                "Dermatologist",
    "Malaria":                 "General Physician",
}